# Generated by Django 5.0.4 on 2024-06-30 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoneuser',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_one_user', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='categoryoneuser',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_one_users', related_query_name='category_one_user', to='category.categoryone'),
        ),
        migrations.AddField(
            model_name='categorytwouser',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_two_user', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='categorytwouser',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_two_users', related_query_name='category_two_user', to='category.categorytwo'),
        ),
        migrations.AddField(
            model_name='subcategorytwo',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_two', related_query_name='sub_category_two', to='category.categorytwo'),
        ),
        migrations.AddField(
            model_name='subcategorytwofile',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_two_files', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='subcategorytwofile',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_two_files', related_query_name='sub_category_two_file', to='category.subcategorytwo'),
        ),
        migrations.AddField(
            model_name='subcategorytwouser',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_category_two_users', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='subcategorytwouser',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_category_two_users', related_query_name='sub_category_two_user', to='category.subcategorytwo'),
        ),
        migrations.AddField(
            model_name='totaldocuser',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='total_doc_user', to='users.studentuser'),
        ),
        migrations.AddField(
            model_name='totaldocuser',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_doc_users', related_query_name='total_doc_user', to='category.totaldoc'),
        ),
    ]
